# This is a basic Clash configuration template.
# Users should customize this based on their needs.

port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: info
external-controller: '0.0.0.0:9090'

proxies:
  # Proxies will be added here by the script from servers.json
  # Example:
  # - name: "Example SS Proxy"
  #   type: ss
  #   server: server.example.com
  #   port: 8888
  #   cipher: aes-256-gcm
  #   password: "your_password"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      # This will be populated with actual proxy names by the script
      # or should be manually set if you have fixed preferred proxies.
      # For dynamic population, ensure your script handles this.
      # Add any specific proxies you want to always be selectable here.
      # - "Example SS Proxy"
  - name: "StreamingServices"
    type: select
    proxies:
      - "PROXY" # Default to main PROXY group, can be more specific
      # - "US-Proxy"
      # - "HK-Proxy"
  - name: "GamingProxies"
    type: select
    proxies:
      - "PROXY"
      # - "LowLatency-Proxy"
  - name: "Telegram"
    type: select
    proxies:
      - "DIRECT"
      - "PROXY"
  - name: "AppleServices"
    type: select
    proxies:
      - "PROXY"
      - "DIRECT"
  - name: "MicrosoftServices"
    type: select
    proxies:
      - "PROXY"
      - "DIRECT"
  - name: "MyTestPolicy"
    type: select
    proxies:
      - "DIRECT"

rules:
  # Rules will be added here by the script from generated_rules.txt
  # Example:
  # - DOMAIN-SUFFIX,google.com,PROXY
  # - DOMAIN-KEYWORD,ads,REJECT
  # - GEOIP,CN,DIRECT
  # - MATCH,PROXY
