port: 7890
socks-port: 7891
mode: rule
external-controller: 127.0.0.1:9090
dns:
  enable: false
  listen: 0.0.0.0:53
  default-nameserver:
    - 114.114.114.114
    - 8.8.8.8
  nameserver:
    - 114.114.114.114
    - 8.8.8.8
