name: Update Static Files

on:
  schedule:
    - cron: '0 * * * *'    # for every hour
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          cd server
          npm ci
      - name: Fetch & Generate
        run: |
          cd server
          node fetch-and-generate.js
      - name: Commit static files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add static/
          git commit -m "Auto update at $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "No changes"
          git push
